name: Build/release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Gcc
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install gcc-multilib g++-multilib

      - name: Set environment variable USE_HARD_LINKS
        run: echo "USE_HARD_LINKS=false" >> $GITHUB_ENV
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          build_script_name: "build"
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          release: ${{ github.event.inputs.release_version }}

